version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always
