version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-postgres
    env_file:   # Use an ENV file to store sensitive information.
      - ../.env
    ports:
      - "5432:5432"
    restart: always
