spring:
  application:
    name: "Just Spring Security"

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

logging:
  level:
    org:
      springframework:
        data:
          jpa: TRACE
        jdbc: TRACE
