server:
  port: 8888

spring:
  application:
    name: "Just Spring Security"

  cloud:
    config:
      server:
        git:
          uri: https://github.com/fResult/Spring-Configuration-Externalization
