spring:
  application:
    name: "Just Spring Security"

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

# Keep users here for learning purposes
app:
  config:
    users:
      - username: alice
        password: password
        roles:
          - USER
      - username: bob
        password: password
        roles:
          - USER
      - username: admin
        password: password
        roles:
          - ADMIN
