spring:
  application:
    name: "Just Spring Security (Test)"

  datasource:
    url: jdbc:h2:mem:testdb-dev
    username: sa
    password:

# Keep users here for learning purposes
app:
  config:
    users:
      - username: test1
        password: password
        roles:
          - USER
      - username: test2
        password: password
        roles:
          - USER
      - username: admintest
        password: password
        roles:
          - ADMIN
