spring:
  application:
    name: "Just Spring Security"

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
