server:
    port: 9002

spring:
  application:
    name: "Just Spring Security"

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: ${POSTGRES_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update
#      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
