spring:
  application:
    name: "Just Spring Security"

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID:DUMMY}
            clientSecret: ${GOOGLE_CLIENT_SECRET:DUMMY}
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube
